### ISSUE TITLE
Question: hadoop2 branch and master branch

### ISSUE THREAD

**Issue by colorant** [linkedin/camus#133]
Hi, I noticed that hadoop2 branch and master branch did not quite match each other in terms of some common codes that do not involve hadoop version differences. 

my question is: what is the strategy of developing new feature or do bug fixing on these two branch? Is there any plan to merge these two branch?

**Comment by ehrlichja** [comment]
I also would like to know the status of hadoop 2 support

**Comment by HenryCaiHaiying** [comment]
The master branch pretty much works for hadoop2 (if you just update the hadoop version in pom.xml).

**Comment by ffchenAtCloudera** [comment]
Hi Henry,
I tried master branch with hadoop-2.6.0. 
The job returned SUCCEED. But topics directory does not generated and from error file named errors-m-00021, I found:
SEQ*com.linkedin.camus.etl.kafka.common.EtlKey5com.linkedin.camus.etl.kafka.common.ExceptionWritable*org.apache.hadoop.io.compress.DefaultCodec7tXsv

Could you help give a guide for how to tracing the root cause?
I was using StringMessageDecoder.java in http://etl.svbtle.com/setting-up-camus-linkedins-kafka-to-hdfs-pipeline. And I started producer with following command:
[hadoop@n087 kafka]$ bin/kafka-console-producer.sh --broker-list localhost:9092 --topic test
[2015-06-17 14:01:51,704] WARN Property topic is not valid (kafka.utils.VerifiableProperties)
This is a testing message

Looking forward to your reply.

Thanks
