### ISSUE TITLE
EtlMultiOutputFormat uses static commiter, can cause problems with testing

### ISSUE THREAD

**Issue by bbaugher** [linkedin/camus#50]
So the code [here](https://github.com/linkedin/camus/blob/master/camus-etl-kafka/src/main/java/com/linkedin/camus/etl/kafka/mapred/EtlMultiOutputFormat.java#L78-L79) holds on to a static commiter object which is only instantiated once (i.e. when null). This can cause problems if you were trying to test this class more than once.

**Comment by arthur-evozon** [comment]
Am I missing something, why does the `com.linkedin.camus.etl.kafka.mapred.EtlMultiOutputFormat#committer` need to be static ?

This is actually causing a bug to occur.

I am using Camus to move data between Kafka and HDFS in the following manner: using the Spring framework, and in particular Spring Batched Jobs, to launch a data ETL between Kafka and HDFS. 
The issue I was seeing was that on the first app startup, it all went fine (the data was moved), but any subsequent Batched Jobs, new data that made its way into Kafka, was not moved into HDFS. And it was caused by exactly this `static com.linkedin.camus.etl.kafka.mapred.EtlMultiOutputFormat.committer`.
Although the Job (CamusJob) was setup from new when running with the ToolRunner, the static `committer` has a reference to the `TaskAttemptContext` (`context` field), but the `MapTask` will have a brand new `TaskAttemptContext` that will have a different Job ID. The `org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.needsTaskCommit(...)` will try to test for a new path (based on the new Job ID) and it will report that there is nothing to commit. The net effect is that the result of the CamusJob will not get moved across to the destination folder, and the new data from Kafka, although seen by Camus, will not appear in the destination path.

Not sure what is your proper working procedure, I am going to mark up a new issue out of this, and will create a pull request. Please advise if there is another mechanism in place. This will save others some time.
